version: '3'

services:

  app:
    image: node:16.14.2-alpine3.15
    container_name: api-valoriza
    command: "npm i"
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app

