version: '3'

services:

  app:
    image: node:16.14.2-alpine3.15
    container_name: api-valoriza
    command: "npm run dev"
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: api-valoriza-db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest